abstract: auto generate the template directory name
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
build_requires: 
  Test::Base: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Sledge-Plugin-AutoTmplDirname
no_index: 
  directory: 
    - inc
    - t
requires: 
  Sledge::Utils: 0
version: 0.01
